Default: &defaults
  database: composer.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Test:
  database: composer_test.sqlite3
  <<: *defaults

Staging:
  database: composer_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: composer_production.sqlite3
  poolsize: 100
  <<: *defaults
