Default: &defaults
  database: substantial.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Test:
  database: substantial_test.sqlite3
  <<: *defaults

Staging:
  database: substantial_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: substantial_production.sqlite3
  poolsize: 100
  <<: *defaults
